_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.18.2
            "6": 4.35.2
            "8":
                - 1
                - 5
            "12": 0.18.2
            "13": darwin-arm64
dropout_rate:
    value: 0.3
embedding_dim:
    value: 300
hidden_dim:
    value: 128
learning_rate:
    value: 0.001
max_seq_len:
    value: 512
n_epochs:
    value: 10
n_layers:
    value: 2
optimizer_choice:
    value: Adam
output_dim:
    value: 1
padding_type:
    value: zeros
patience:
    value: 3
train_batch_size:
    value: 32
val_batch_size:
    value: 32
weight_decay:
    value: 0.01
