_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.2
            "6": 4.35.2
            "8":
                - 1
                - 5
            "12": 0.18.2
            "13": darwin-arm64
dropout_rate:
    value: 0.369361420053225
embedding_dim:
    value: 300
hidden_dim:
    value: 187
learning_rate:
    value: 7.589779136468623e-05
max_seq_len:
    value: 512
n_epochs:
    value: 10
n_layers:
    value: 1
optimizer_choice:
    value: SGD
patience:
    value: 3
train_batch_size:
    value: 32
val_batch_size:
    value: 32
weight_decay:
    value: 7.264248703440585e-06
