_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": confusion_matrix.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": confusion_matrix.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": confusion_matrix.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": confusion_matrix._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": confusion_matrix.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": confusion_matrix.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": confusion_matrix.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 51
                - 53
                - 55
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 49
                - 51
                - 53
                - 55
                - 103
                - 106
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
classifier_hidden_dim:
    value: 64
dropout_rate:
    value: 0.1
embedding_dim:
    value: 256
learning_rate:
    value: 1e-05
num_classes:
    value: 2
num_heads:
    value: 16
num_layers:
    value: 6
transformer_hidden_dim:
    value: 1024
vocab_size:
    value: 28996
warmup_steps:
    value: 1000
weight_decay:
    value: 0.0001
